stages:
  - build
  - test

## Set environment variables for folders in "cache" job settings for npm modules and Cypress binary
variables:
  npm_config_cache: '$CI_PROJECT_DIR/.npm'
  CYPRESS_CACHE_FOLDER: '$CI_PROJECT_DIR/cache/Cypress'

# Cache using branch name
# https://gitlab.com/help/ci/caching/index.md
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .cache/*
    - cache/Cypress
    - node_modules

install:
  image: cypress/base:16.14.2-slim
  stage: build
  script:
    # install dependencies
    - npm ci
    # print Cypress binary path and cached versions
    - npx cypress cache path
    - npx cypress cache list

test:
  image: cypress/base:16.14.2-slim
  stage: test
  script:
    # print CI environment variables
    # https://docs.gitlab.com/ee/ci/variables/predefined_variables.html
    - npx @bahmutov/print-env CI_
    - npx cypress run -e split=true,TAGS="$VG" --browser chrome --spec "cypress/e2e/features/00_common/*.feature";
  parallel:
    matrix:
      - VG: ['GB','US']
        containers: [1, 2, 3, 4]
  variables:
    REPORT_SUFFIX: "$VG"
